services:
  - type: web
    name: proagendify-backend
    env: node
    region: sao1
    buildCommand: cd backend && npm install && chmod +x render-build.sh && ./render-build.sh
    startCommand: cd backend && npx prisma migrate deploy && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 18.x
      - key: PORT
        value: 3333
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 1d
      - key: REDIS_URL
        sync: false
      - key: ALLOWED_ORIGINS
        value: https://proagendify-frontend.vercel.app,https://proagendify.vercel.app
      - key: FRONTEND_URL
        value: https://proagendify-frontend.vercel.app
    healthCheckPath: /api/health-check 